package models;
// Generated 24 mars 2014 10:24:07 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Connected generated by hbm2java
 */
@Entity
@Table(name="connected")
public class Connected  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@Id 
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "id")
	private Integer connectedId;
	
	@Column(name = "id_User", columnDefinition="Integer(11) ", nullable=false)
    private Integer connectedIdUser;
	
	@Column(name = "Adresse_Ip", columnDefinition="varchar(40) default '' ", nullable=false)
    private String connectedIp;
	
	@Column(name = "Temps_Connexion", columnDefinition="varchar(80) default '' ", nullable=false)
    private Long connectedTime;

    public Connected() {
    }

    public Connected(Integer connectedIdUser, String connectedIp, Long connectedTime) {
       this.connectedIdUser = connectedIdUser;
       this.connectedIp = connectedIp;
       this.connectedTime = connectedTime;
    }
   
   
    public Integer getConnectedId() {
        return this.connectedId;
    }
    
    public void setConnectedId(Integer connectedId) {
        this.connectedId = connectedId;
    }

    
    public Integer getConnectedIdUser() {
        return this.connectedIdUser;
    }
    
    public void setConnectedIdUser(Integer connectedIdUser) {
        this.connectedIdUser = connectedIdUser;
    }


    public String getConnectedIp() {
        return this.connectedIp;
    }
    
    public void setConnectedIp(String connectedIp) {
        this.connectedIp = connectedIp;
    }


    public Long getConnectedTime() {
        return this.connectedTime;
    }
    
    public void setConnectedTime(Long connectedTime) {
        this.connectedTime = connectedTime;
    }

}